import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "@/components/wallet-provider";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "Liquidate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} ${spaceGrotesk.className} antialiased`}
      >
        <AppWalletProvider>
        {children}
        </AppWalletProvider>
        
      </body>
    </html>
  );
}
